# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a set of commands using the runners shell
      - name: build-linux
        id: build-linux
        run: |
          sudo docker ps 
          pwd
          sudo docker run --rm --name build-linux --privileged=true -v /home/gitlab-runner/actions-runner/_work/DC-linux/DC-linux:/home  main-linux:v1 /bin/bash -c "cd /home && export ARCH=riscv && export CROSS_COMPILE=/usr/bin/riscv64-linux-gnu- && make defconfig && make -j$(nproc) && make modules_install"
          sudo chown -R gitlab-runner:gitlab-runner /home/gitlab-runner/actions-runner/_work/DC-linux/DC-linux  
          sudo chmod -R 755 /home/gitlab-runner/actions-runner/_work/DC-linux/DC-linux
      - name: send-mail
        if: ${{ failure() && steps.build-linux.conclusion == 'failure' }}
        env: 
            email: "sixue.cheng@deepcomputing.io"
        run: |
          echo $email
          echo "CI build code failure ! https://github.com/DC-DeepComputing/test-action/actions" | mail -s "build code" $email
          
